// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddInstructor(arg1:string):Promise<models.Instructor>;

export function CloseDB():Promise<void>;

export function DeleteInstructor(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetAllInstructors():Promise<Array<models.Instructor>>;

export function GetInstructor(arg1:string):Promise<models.Instructor>;

export function GetSession(arg1:string):Promise<models.Session>;

export function GetSessions():Promise<Array<models.Session>>;

export function GetUser(arg1:string):Promise<models.User>;

export function GetUsers():Promise<Array<models.User>>;

export function InitializeDB(arg1:string):Promise<void>;

export function LoginUserCommand(arg1:string,arg2:string):Promise<models.User>;

export function Logout():Promise<void>;

export function RegisterUserCommand(arg1:string,arg2:string,arg3:models.UserRole):Promise<void>;

export function SessionActivate():Promise<void>;

export function SessionDeactivate():Promise<void>;

export function SessionState():Promise<boolean>;

export function SessionTerminate():Promise<void>;

export function SetSession(arg1:models.Session):Promise<void>;

export function UpdateInstructor(arg1:models.Instructor):Promise<void>;
