// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInstructor(arg1) {
  return window['go']['backend']['App']['AddInstructor'](arg1);
}

export function CheckIfNeedsSetup() {
  return window['go']['backend']['App']['CheckIfNeedsSetup']();
}

export function CloseDB() {
  return window['go']['backend']['App']['CloseDB']();
}

export function DeleteInstructor(arg1) {
  return window['go']['backend']['App']['DeleteInstructor'](arg1);
}

export function GetAllInstructors() {
  return window['go']['backend']['App']['GetAllInstructors']();
}

export function GetInstructor(arg1) {
  return window['go']['backend']['App']['GetInstructor'](arg1);
}

export function GetSession(arg1) {
  return window['go']['backend']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['backend']['App']['GetSessions']();
}

export function GetUsers() {
  return window['go']['backend']['App']['GetUsers']();
}

export function InitializeDB(arg1) {
  return window['go']['backend']['App']['InitializeDB'](arg1);
}

export function LoginUserCommand(arg1, arg2) {
  return window['go']['backend']['App']['LoginUserCommand'](arg1, arg2);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function RegisterUserCommand(arg1, arg2) {
  return window['go']['backend']['App']['RegisterUserCommand'](arg1, arg2);
}

export function SessionActivate() {
  return window['go']['backend']['App']['SessionActivate']();
}

export function SessionDeactivate() {
  return window['go']['backend']['App']['SessionDeactivate']();
}

export function SessionState() {
  return window['go']['backend']['App']['SessionState']();
}

export function SessionTerminate() {
  return window['go']['backend']['App']['SessionTerminate']();
}

export function SetSession(arg1) {
  return window['go']['backend']['App']['SetSession'](arg1);
}

export function UpdateInstructor(arg1) {
  return window['go']['backend']['App']['UpdateInstructor'](arg1);
}
